version: '3.8'

services:
  proxy-service:
    build:
      context: ./proxy
    container_name: proxy-service
    hostname: proxy-service
    ports:
      - "8080:8080"
    networks:
      proxy:
        ipv4_address: 172.21.0.5

  downstream-service:
    build:
      context: ./downstream
    container_name: downstream
    hostname: downstream
    ports:
      - "8081:8081"
    networks:
      proxy:
        ipv4_address: 172.21.0.6

networks:
  proxy:
    ipam:
      config:
        - subnet: 172.21.0.0/24